// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo0mPARcRx34bhCmo87rVRJhlw-sB4HDI',
    appId: '1:152854806792:web:b8e29a9b32f011b08f6cbd',
    messagingSenderId: '152854806792',
    projectId: 'last-dearus',
    authDomain: 'last-dearus.firebaseapp.com',
    storageBucket: 'last-dearus.firebasestorage.app',
    measurementId: 'G-3N8ZGC86T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZXVLw6ar7nAXUNXtXyOCezbKzZO7JGtk',
    appId: '1:152854806792:android:cf8213defa684fb68f6cbd',
    messagingSenderId: '152854806792',
    projectId: 'last-dearus',
    storageBucket: 'last-dearus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn8T8NtbHrAvQie0i3OcPgzvQlbj6tH5Y',
    appId: '1:152854806792:ios:2a18baaa051216ce8f6cbd',
    messagingSenderId: '152854806792',
    projectId: 'last-dearus',
    storageBucket: 'last-dearus.firebasestorage.app',
    iosBundleId: 'com.example.lastDearUs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn8T8NtbHrAvQie0i3OcPgzvQlbj6tH5Y',
    appId: '1:152854806792:ios:2a18baaa051216ce8f6cbd',
    messagingSenderId: '152854806792',
    projectId: 'last-dearus',
    storageBucket: 'last-dearus.firebasestorage.app',
    iosBundleId: 'com.example.lastDearUs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo0mPARcRx34bhCmo87rVRJhlw-sB4HDI',
    appId: '1:152854806792:web:18d8ce1fda5583bc8f6cbd',
    messagingSenderId: '152854806792',
    projectId: 'last-dearus',
    authDomain: 'last-dearus.firebaseapp.com',
    storageBucket: 'last-dearus.firebasestorage.app',
    measurementId: 'G-ZBL7FZMZVX',
  );
}
